version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - shared-data:/shared:data
  etl:
    build:
      context: ./pipeline_carga_dados
      dockerfile: dockerfile
    volumes:
      - shared-data:/shared:data
  
volumes:
  shared-data: