version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
  etl:
    build:
      context: ./pipeline_carga_dados
      dockerfile: dockerfile
    volumes:
      - .:/pipeline_carga_dados