# Use uma imagem base do Python
FROM python:3.10.13-slim

# Defina o diretório de trabalho no contêiner
WORKDIR /home/project

#Install Cron
RUN apt-get update
RUN apt-get -y install cron

# Add the cron job
RUN crontab -l | { cat; echo "0 12 * * * /usr/local/bin/python /home/project/pipeline.py >> /var/log/cron.log 2>&1"; } | crontab -

# Copie os arquivos do projeto para o contêiner
COPY . /home/project

# Copy your cron job file into the container
COPY crontab /etc/cron.d/crontab

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/crontab

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Instale as bibliotecas necessárias
RUN pip install --upgrade pip
RUN pip install pandas \
               lxml \
               prophet \
               plotly \
               plotly.express \
               numpy \
               pandas-gbq -U

CMD ["cron", "-f"]
